import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import {mkdtemp,writeFile} from 'node:fs/promises';import path from 'node:path';
const profile=await mkdtemp(path.resolve('desktop/test-output/catalogue-ui-'));const errors=[];const checks=[];
const app=await electron.launch({args:['.'],env:{...process.env,OPENGYM_TEST_DATA:profile}});
try{const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Сегодня',exact:true}).waitFor();await page.getByRole('button',{name:'Мои упражнения',exact:true}).click();await page.locator('.desk-exercise-row').first().waitFor();assert(await page.getByRole('button',{name:'Гантели, свой вес и дорожка',exact:true}).getAttribute('aria-pressed')==='true');
await page.getByRole('button',{name:/^Плечи\s/}).click();await page.locator('.desk-exercise-row[data-exercise-id="0426"]').click();await page.getByRole('heading',{name:'Жим гантелей над головой стоя',exact:true}).waitFor();await page.locator('.catalogue-instructions summary').click();assert(await page.locator('.catalogue-instructions li').count()>2);const text=await page.locator('.catalogue-instructions li').first().innerText();assert(/[А-Яа-я]/.test(text));checks.push('Shoulders group, Russian overhead press card and Russian steps');
await page.getByLabel('Как я называю упражнение',{exact:true}).fill('Мой жим вверх');await page.getByLabel('Мой отдых между подходами, сек',{exact:true}).fill('180');await page.getByRole('button',{name:'Добавить в мой список',exact:true}).click();await page.getByText('Сохранено. Напарник знает это название.',{exact:true}).waitFor();await page.getByRole('button',{name:/^Мой список ·/}).click();assert.equal(await page.locator('.desk-exercise-row').count(),1);await page.getByLabel('Поиск упражнений',{exact:true}).fill('мой жим');assert.equal(await page.locator('.desk-exercise-row').count(),1);checks.push('Personal name/rest save and shortlist search');
await page.getByRole('button',{name:'Каталог',exact:true}).click();await page.getByLabel('Поиск упражнений',{exact:true}).fill('несуществующеедвижение');await page.getByRole('heading',{name:'Ничего не найдено',exact:true}).waitFor();await page.getByRole('button',{name:'Открыть весь каталог',exact:true}).click();await page.getByRole('button',{name:/^Спина\s/}).click();assert(await page.locator('.desk-exercise-row').count()>0);assert((await page.locator('.desk-exercise-row b').allTextContents()).every(n=>!/[A-Za-z]/.test(n)));checks.push('All-equipment catalogue, empty recovery, Russian visible results');
for(const width of [1366,820]){await app.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows()[0].setSize(width,900),width);await page.waitForTimeout(150);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`desktop/test-output/catalogue-${width}.png`})}checks.push('1366/820px no overflow');
const s=(await page.evaluate(()=>window.openGymDesktop.load())).state;assert.equal(s.desktopExerciseNames['0426'],'Мой жим вверх');assert.equal(s.desktopRestOverrides['0426'],180);assert.equal(s.workouts.length,0);assert.equal(errors.length,0,errors.join('\n'));await writeFile('desktop/test-output/catalogue-ui-report.json',JSON.stringify({passed:true,profile,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks}));}finally{await app.close()}
