import { _electron as electron } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir, mkdtemp, readFile, writeFile, cp, access } from 'node:fs/promises'
import path from 'node:path'

const output = path.resolve('desktop/test-output')
await mkdir(output, { recursive: true })
const profile = await mkdtemp(path.join(output, 'smoke-profile-'))
// Optional local fixture downloaded through the real media module, never required by the test.
try { await access(path.join(output, 'offline-media')); await cp(path.join(output, 'offline-media'), path.join(profile, 'media'), { recursive: true }) } catch {}
const errors = [], requests = [], checks = []
let app, page
const launch = async () => {
  app = await electron.launch({ args: ['.'], env: { ...process.env, OPENGYM_TEST_DATA: profile } })
  page = await app.firstWindow()
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.url().includes('/api/') || /^https?:/.test(r.url())) requests.push(r.url()) })
  await page.getByRole('heading', { name: /Домашние тренировки/ }).waitFor()
  await page.locator('.desk-save.saved').waitFor()
}
const shot = async name => { await page.waitForTimeout(300); await page.screenshot({ path: path.join(output, name + '.png'), fullPage: true }) }
const noOverflow = async () => assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'horizontal overflow')
try {
  await launch()
  await page.context().setOffline(true)
  await noOverflow(); await shot('01-home-empty')
  await page.evaluate(() => document.fonts.ready)
  assert(await page.evaluate(() => document.fonts.check('600 16px Manrope', 'Тренировка') && document.fonts.check('700 24px Unbounded', 'Домашние')))
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('DOM.enable'); await cdp.send('CSS.enable')
  const { root } = await cdp.send('DOM.getDocument')
  for (const [selector, family] of [['h1', 'Unbounded'], ['.desk-nav-item', 'Manrope']]) {
    const { nodeId } = await cdp.send('DOM.querySelector', { nodeId: root.nodeId, selector })
    const { fonts } = await cdp.send('CSS.getPlatformFontsForNode', { nodeId })
    assert(fonts.some(f => f.familyName.includes(family) && f.isCustomFont), family + ' must actually render text')
  }
  await cdp.detach()
  checks.push('Fresh profile: zero fabricated workouts, offline initial load, isolated disk storage')
  await page.getByRole('button', { name: 'Подобрать домашний план' }).click()
  await page.getByRole('button', { name: 'Добавить в мой план' }).waitFor()
  await shot('02-plan-preview')
  await page.getByRole('button', { name: 'Добавить в мой план' }).click()
  await page.locator('.desk-save.saved').waitFor()
  assert.equal(await page.locator('.routine-folder').count(), 4)
  await page.getByRole('tab', { name: 'Неделя', exact: true }).click()
  assert.equal(await page.locator('.workspace-week .week-date').count(), 7)
  await shot('week-schedule')
  await page.getByRole('tab', { name: 'Последние занятия', exact: true }).click()
  await page.getByRole('heading', { name: 'Занятий ещё нет' }).waitFor()
  await page.getByRole('tab', { name: /Программы/ }).click()
  await page.getByRole('button', { name: 'Выбрать: Тортик', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: 'Выбрать: Тортик', exact: true }).getAttribute('aria-pressed'), 'true')
  await page.getByRole('button', { name: /На рабочий стол/ }).click()
  let widget = app.windows().find(w => w.url().includes('/widget/'))
  if (!widget) widget = await app.waitForEvent('window', { predicate: w => w !== page })
  await widget.waitForLoadState('domcontentloaded')
  await widget.locator('#mascot').waitFor()
  await widget.waitForFunction(() => document.querySelector('#mascot').alt === 'Тортик')
  assert.equal(await widget.evaluate(() => typeof window.openGymDesktop), 'undefined')
  await widget.getByRole('button', { name: 'Сменить персонажа' }).click()
  await page.waitForFunction(() => document.querySelector('.buddy-pick.burger').getAttribute('aria-pressed') === 'true')
  await widget.getByRole('button', { name: 'Поверх всех окон' }).click()
  await widget.waitForFunction(() => document.querySelector('#pin').getAttribute('aria-pressed') === 'true')
  await widget.getByRole('button', { name: 'Разминка · 2 минуты' }).click()
  await widget.waitForFunction(() => document.querySelector('#detail').textContent === 'Разминка с Тортиком')
  assert(await widget.evaluate(() => document.documentElement.scrollHeight <= innerHeight && document.documentElement.scrollWidth <= innerWidth), 'Widget must not scroll')
  await widget.screenshot({ path: path.join(output, 'widget-warmup.png') })
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await widget.waitForFunction(() => document.querySelector('#value').textContent === 'Погнали?')
  await widget.getByRole('button', { name: 'Скрыть виджет' }).click()
  checks.push('Embedded Cyrillic fonts load offline; cake/burger selection syncs; native widget pin and warmup work')
  await shot('02b-home-reference')
  await page.getByRole('button', { name: 'Начать', exact: true }).first().click()
  await page.locator('.desk-workout-outline button').nth(1).click()
  await page.locator('.workout-swipe-surface').getByText('Тяга гантелей в наклоне', { exact: true }).waitFor()
  await page.locator('.desk-workout-outline button').first().click()
  checks.push('Workspace tabs expose real schedule/empty history; exercise outline switches active exercise')
  await page.getByRole('checkbox').first().waitFor()
  await page.getByRole('checkbox').first().click()
  await page.locator('.desk-save.saved').waitFor()
  const active = JSON.parse(await readFile(path.join(profile, 'training.json'), 'utf8'))
  assert(active.active.entries[0].sets[0].done)
  await shot('03-workout-active')
  checks.push('Home plan: 4 routines, Mon/Wed/Fri; starts offline, set logged and persisted')
  await app.close()
  await launch()
  await page.locator('.workspace-resume').click()
  assert.equal(await page.getByRole('checkbox').first().getAttribute('aria-checked'), 'true')
  checks.push('Active session survives complete app restart with checked set')
  const widgetOpening = app.waitForEvent('window')
  await page.getByRole('button', { name: /На рабочий стол/ }).click()
  const runningWidget = await widgetOpening
  await runningWidget.waitForURL('**/widget/index.html')
  await runningWidget.waitForFunction(() => document.querySelector('#value').textContent === '1 / 9')
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html#/workout')).close())
  await page.waitForTimeout(200)
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => !w.webContents.getURL().includes('/widget/')).isVisible()), false)
  await runningWidget.getByRole('button', { name: 'Вернуться к тренировке ↗', exact: true }).click()
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => !w.webContents.getURL().includes('/widget/')).isVisible()), true)
  await runningWidget.getByRole('button', { name: 'Скрыть виджет' }).click()
  checks.push('Native widget displays real completed sets, survives main-window close and reopens the active workout')
  await page.getByRole('button', { name: 'Завершить', exact: true }).click()
  const finish = page.getByRole('button', { name: 'Завершить тренировку', exact: true })
  await finish.click()
  await page.locator('.desk-save.saved').waitFor()
  const completed = JSON.parse(await readFile(path.join(profile, 'training.json'), 'utf8'))
  assert.equal(completed.workouts.length, 1)
  assert.equal(completed.active, null)
  checks.push('Finish session creates history entry and clears active session')
  await app.close()
  await launch()
  await page.locator('.desk-sidebar').getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByPlaceholder('Имя (необязательно)').fill('Тестовый профиль')
  await page.getByLabel('Тема', { exact: true }).selectOption('dark')
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark')
  await shot('04-settings-dark')
  const backupPath = path.join(output, 'export-test.json')
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }) }, backupPath)
  await page.getByRole('button', { name: 'Экспортировать', exact: true }).click()
  await page.getByText('Резервная копия сохранена', { exact: true }).waitFor()
  const backup = JSON.parse(await readFile(backupPath, 'utf8'))
  assert.equal(backup.workouts.length, 1)
  const badPath = path.join(output, 'bad-import.json')
  await writeFile(badPath, '{"routines":[]}')
  await app.evaluate(({ dialog }, filePath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filePath] }) }, badPath)
  await page.getByRole('button', { name: 'Восстановить', exact: true }).click()
  await page.getByRole('alert').getByText('Действие не выполнено').waitFor()
  assert.equal(JSON.parse(await readFile(path.join(profile, 'training.json'), 'utf8')).workouts.length, 1)
  checks.push('Native backup export contains training history; invalid import rejected without data loss')
  await app.evaluate(({ dialog }, filePath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filePath] }) }, backupPath)
  await page.getByRole('button', { name: 'Восстановить', exact: true }).click()
  await page.locator('.center').getByRole('button', { name: 'Восстановить', exact: true }).click()
  await page.getByText('Данные восстановлены', { exact: true }).waitFor()
  assert.equal(JSON.parse(await readFile(path.join(profile, 'training.json'), 'utf8')).workouts.length, 1)
  checks.push('Valid backup restores after preview/confirmation and keeps history')
  await page.locator('.desk-sidebar').getByRole('button', { name: 'Обзор', exact: true }).click()
  await shot('05-home-dark')
  await page.keyboard.press('Control+k')
  await page.getByPlaceholder('Найти раздел или программу…').fill('журнал')
  await page.keyboard.press('Enter')
  await page.waitForURL('**#/history')
  checks.push('Ctrl+K searches routes and opens history using keyboard')
  for (const [label, route] of [['Мой план', 'plan'], ['Упражнения', 'library'], ['Прогресс', 'stats'], ['Настройки', 'settings']]) {
    await page.locator('.desk-sidebar').getByRole('button', { name: label, exact: true }).click()
    await page.waitForURL('**#/' + route)
    await noOverflow(); await shot('route-' + route)
    if (route === 'plan') {
      const pdfPath = path.join(output, 'plan-test.pdf')
      await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }) }, pdfPath)
      await page.getByRole('button', { name: 'Поделиться планом' }).click()
      await page.getByRole('button', { name: 'Печать / Сохранить как PDF' }).click()
      await page.getByText('План сохранён в PDF', { exact: true }).waitFor()
      assert.equal((await readFile(pdfPath)).subarray(0, 4).toString(), '%PDF')
      checks.push('Plan export generates a real PDF through the native save dialog')
    }
    if (route === 'library') {
      await page.getByPlaceholder('Поиск…').fill('приседание с гантелью')
      await page.getByText('Приседание с гантелью', { exact: true }).waitFor()
      await shot('library-russian-search')
      await page.getByPlaceholder('Поиск…').fill('zzzznotanexercise')
      await page.locator('.empty').waitFor()
      checks.push('Home exercise search supports Russian names and empty results')
    }
  }
  await page.getByLabel('Тема', { exact: true }).selectOption('light')
  await page.getByRole('button', { name: 'Все настройки тренировок' }).click()
  await page.waitForURL('**#/settings/advanced')
  assert.equal(await page.getByText('Гостевой режим', { exact: false }).count(), 0)
  await shot('06-advanced-settings')
  await page.locator('.desk-sidebar').getByRole('button', { name: 'Обзор', exact: true }).click()
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(820, 720))
  await noOverflow()
  assert.equal(await page.locator('.desk-brand>span').last().isVisible(), false)
  assert.equal(await page.locator('.desk-nav-item>span').first().isVisible(), false)
  assert(await page.evaluate(() => document.querySelector('.desk-sidebar').getBoundingClientRect().right <= document.querySelector('#app').getBoundingClientRect().left), 'Sidebar must not cover content')
  await shot('07-compact-window')
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1380, 920))
  await shot('08-home-light')
  checks.push('Plan/library/stats/settings render; light/dark and 820px window have no horizontal overflow')
  await page.locator('.routine-folder-name').first().click()
  assert.equal(await page.locator('.desktop-delete-row').count(), 5)
  await page.locator('.desktop-delete-row>.iconbtn').last().click()
  assert.equal(await page.locator('.desktop-delete-row').count(), 4)
  await page.locator('.desk-save.saved').waitFor()
  checks.push('Desktop routine editor exposes mouse/keyboard delete control and persists exercise removal')
  assert.equal(errors.length, 0, JSON.stringify(errors))
  assert.equal(requests.length, 0, JSON.stringify(requests))
  checks.push('No renderer exceptions, no backend API or external network requests in core workflow')
  await writeFile(path.join(output, 'smoke-report.json'), JSON.stringify({ checks, errors, requests, profile }, null, 2))
  console.log(JSON.stringify({ checks, errors, requests }, null, 2))
} finally { if (app) await app.close().catch(() => {}) }
