import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import {mkdtemp,writeFile} from 'node:fs/promises';import path from 'node:path';
const profile=await mkdtemp(path.resolve('desktop/test-output/today-ui-'));const errors=[];
const app=await electron.launch({args:['.'],env:{...process.env,OPENGYM_TEST_DATA:profile}});
try{const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Сегодня',exact:true}).waitFor();assert.equal(await page.locator('nav[aria-label="Основная навигация"] button').count(),3);await page.getByText('Пока ни одного подхода',{exact:true}).waitFor();await page.screenshot({path:'desktop/test-output/today-empty.png'});
await page.getByRole('button',{name:'Мои упражнения',exact:true}).click();await page.getByLabel('Поиск упражнений',{exact:true}).fill('Жим гантелей');await page.locator('.desk-exercise-row[data-exercise-id="0426"]').click();await page.getByLabel('Как я называю упражнение',{exact:true}).fill('Мой жим вверх');
const restInput=page.locator('.desk-exercise-preview input[type="number"]');await restInput.fill('180');await page.getByRole('button',{name:'Добавить в мой список',exact:true}).click();await page.getByText('Сохранено. Напарник знает это название.',{exact:true}).waitFor();await page.getByRole('button',{name:/^Мой список ·/}).click();await page.locator('.desk-exercise-row').filter({hasText:'Мой жим вверх'}).waitFor();
let state=(await page.evaluate(()=>window.openGymDesktop.load())).state;assert.equal(state.desktopExerciseNames['0426'],'Мой жим вверх');assert.equal(state.desktopRestOverrides['0426'],180);assert.deepEqual(state.desktopFavorites,['0426']);await page.locator('.desk-exercise-row').first().click();await page.screenshot({path:'desktop/test-output/exercises-personal.png'});
for(const width of [1366,820]){await app.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows()[0].setSize(width,900),width);await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
await page.getByRole('button',{name:'Сегодня',exact:true}).click();await page.getByRole('button',{name:'Предыдущий день'}).click();await page.getByText('За выбранный день выполненных подходов нет.').waitFor();await page.getByRole('button',{name:'К сегодняшнему дню',exact:true}).click();await page.getByRole('heading',{name:'Сегодня',exact:true}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'desktop/test-output/today-compact.png'});
assert.equal(errors.length,0,errors.join('\n'));await writeFile('desktop/test-output/today-ui-report.json',JSON.stringify({passed:true,profile,checks:['Three main tabs','Empty day no seeded content','Personal exercise name and 180s rest persist','Calendar changes empty day','1366 and 820px no overflow'],rendererErrors:errors},null,2));console.log('Today UI PASS');}finally{await app.close()}
